language: java
jdk:
  - oraclejdk8
script:
  mvn test -Dmaven.test.skip=false -fae

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "lCkt50yiukHEcjBwDpRXPCQSE/ASf0gCYoxZq8fq5cuXcVMoD4h3uIhOuKmUy3+dWbLWNtVE061/uKX3Hr0uT2flhYdeD+yT9HS408SF3OnMFJHMYlQSmSA+EADH8JQjKPGhSFxVwhr4bVThYig3G0WjeFOrlDV+VDJpa/+/4ZI="

addons:
  coverity_scan:
    project:
      name: "subchen/jetbrick-commons"
      description: "Build submitted via Travis CI"
    notification_email: subchen@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -Dmaven.test.skip=false compile"
    branch_pattern: master
